#ifndef PROPERTIES_H
#define PROPERTIES_H

#include "agioproperty.h"
#include "agiosettings.h"

extern AgIOProperty property_setUDP_listenPort;
extern AgIOProperty property_setUDP_sendPort;
extern AgIOProperty property_setUDP_numConnections;
extern AgIOProperty property_setUDP_IP1;
extern AgIOProperty property_setUDP_IP2;
extern AgIOProperty property_setUDP_IP3;
extern AgIOProperty property_setLoop_listenPort;
extern AgIOProperty property_setLoop_sendPort;
extern AgIOProperty property_setNTRIP_isOn;
extern AgIOProperty property_setRadio_isOn;
extern AgIOProperty property_setSerialPass_isOn;
extern AgIOProperty property_setNTRIP_casterPort;
extern AgIOProperty property_setNTRIP_mount;
extern AgIOProperty property_setNTRIP_userName;
extern AgIOProperty property_setNTRIP_userPassword;
extern AgIOProperty property_setNTRIP_sendToUDPPort;
extern AgIOProperty property_setNTRIP_sendGGAInterval;
extern AgIOProperty property_setNTRIP_isGGAManual;
extern AgIOProperty property_setNTRIP_manualLat;
extern AgIOProperty property_setNTRIP_manualLon;
extern AgIOProperty property_setNTRIP_isTCP;
extern AgIOProperty property_setNTRIP_isHTTP10;
extern AgIOProperty property_setNTRIP_ipAddress;
extern AgIOProperty property_setNTRIP_url;

#endif
